name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    # CHECK via OWLReasoner (consistency and all of its classes are satisfiable)
    - run: java -jar ./bin/OntologyChecker.jar ./rdf/knowledge.ttl

    # CHECK via SHACL (use Apache Jena's SHACL implementation)
    - run: ./bin/apache-jena-4.6.1/bin/shacl validate --data ./rdf/knowledge.ttl --shapes ./rdf/knowledge-shacl.ttl

    # CHECK via SHACL (use Apache Jena's SHACL implementation)
    - run: ./bin/apache-jena-4.6.1/bin/sparql --data=./rdf/knowledge-for-sparql.ttl --query=./sparql/query1.sparql
