name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    # check that knowledge file is consistent and all of its classes are satisfiable
    - run: java -jar bin/Checker.jar
    # download Apache Jena (with SHACL bin)
    - run: wget -c https://dlcdn.apache.org/jena/binaries/apache-jena-4.4.0.tar.gz -O - | tar -xz && mv apache-jena-4.4.0 apache-jena
    # Validate knowledge.ttl using SHACL shapes from knowledge-shacl.ttl
    - run: ./apache-jena/bin/shacl validate --data knowledge.ttl --shapes knowledge-shapes.ttl
