name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    # check that knowledge file is consistent and all of its classes are satisfiable
    - run: java -jar bin/OntologyChecker.jar knowledge.ttl

    # Validate knowledge.ttl using (Apache Jena's) SHACL shapes from knowledge-shacl.ttl
    - run: ./bin/apache-jena-4.6.1/bin/shacl validate --data knowledge.ttl --shapes knowledge-shacl.ttl
